### ISSUE TITLE
Doesn't compile with Erlang 23.0

### ISSUE THREAD

**Issue by mdimas** [Ianleeclark/Paseto#35]
It looks like the libsalty dependency is incompatible with Erlang 23.0.

```
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [priv/salty_nif.so] Error 1
```

**Comment by Ianleeclark** [comment]
Hey there,

I had issues replicating this, see:

```bash
ian@botnet ~/Development/personal/paseto
 % erl --version
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1>  
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
ian@botnet ~/Development/personal/paseto
 % elixir --version
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 20)
ian@botnet ~/Development/personal/paseto
 % mix compile   
ian@botnet ~/Development/personal/paseto
 % $!
zsh: command not found: 0
```

Could you let me know which version of libsodium you're using? You could probably do something like `grep "VERSION" /usr/local/include/sodium/version.h`

**Comment by Ianleeclark** [comment]
After fiddling with this some more, I was able to replicate the error. I'm going to see if I can fix it, but the short-term fix might be a little difficult to get out, as the `libsalty` project is no longer maintained. I'm seeing if I can become a maintainer of that project so that I can get it fixed upstream, otherwise I'll fork it and force a workaround that way.

**Comment by mdimas** [comment]
I was able to get it to compile if I compiled with 22.3 first, and then switched to 23.0 and compiled again. I'm pretty new to elixir and erlang, so am not sure what is happening in that condition. If I start clean and compile with 23.0 I get the error though, and it sounds like you were able to reproduce that.

I ran into the same thing as you about the `libsalty` project, which is why I opened the issue here instead of there. Happy to see the quick response! Let me know if there's anything else I can do to help.

**Comment by Ianleeclark** [comment]
It doesn't appear that the old author has any interest in offering maintainership, so I'll be forking the project, fixing the bug, and releasing it sometime this week.

**Comment by Ianleeclark** [comment]
Updated in v1.3.1

**Comment by yordis** [comment]
@Ianleeclark would you mind help with Ueberauth https://github.com/ueberauth/guardian_paseto/actions/runs/1352057780

We are having this issue in CI
